import Home from "./Home/Home";
import Team from "./Team/Team";
import Events from "./Events/Events";
import Youth from "./Youth/Youth";
import Mockmun from "./Mockmun/Mockmun";
import Annual from "./Annual/First";
import Contact from "./Contact/Contact";
import About from "./About/About";
import Gallery from "./Gallery/Gallery";
export { Home, Team, Events, Youth, Mockmun, Annual, Contact, About, Gallery };
